name: go

on:
  workflow_dispatch:
    inputs:
      go_version:
        required: false
        type: string
        default: '1.20'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: ${{ inputs.go_version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Tidy
        run: |
          go mod init github.com/zeyac/gore
          #go mod init github.com/zeyac/brow
          #go mod tidy
      -
        name: Set up Git
        run: |
          git config user.name GitHub
          git config user.email noreply@github.com
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git
      -
        name: Commit and push changes
        run: |
          git add .
          git commit --author "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
